// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/rating/v1/rating.proto

package ratingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRatingRequest) Reset() {
	*x = GetPlayerRatingRequest{}
	mi := &file_proto_rating_v1_rating_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRatingRequest) ProtoMessage() {}

func (x *GetPlayerRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_v1_rating_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRatingRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRatingRequest) Descriptor() ([]byte, []int) {
	return file_proto_rating_v1_rating_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerRatingRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type GetPlayerRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Rating        int32                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	GamesPlayed   int32                  `protobuf:"varint,3,opt,name=games_played,json=gamesPlayed,proto3" json:"games_played,omitempty"`
	Wins          int32                  `protobuf:"varint,4,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses        int32                  `protobuf:"varint,5,opt,name=losses,proto3" json:"losses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRatingResponse) Reset() {
	*x = GetPlayerRatingResponse{}
	mi := &file_proto_rating_v1_rating_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRatingResponse) ProtoMessage() {}

func (x *GetPlayerRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rating_v1_rating_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRatingResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerRatingResponse) Descriptor() ([]byte, []int) {
	return file_proto_rating_v1_rating_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayerRatingResponse) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *GetPlayerRatingResponse) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GetPlayerRatingResponse) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *GetPlayerRatingResponse) GetWins() int32 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *GetPlayerRatingResponse) GetLosses() int32 {
	if x != nil {
		return x.Losses
	}
	return 0
}

var File_proto_rating_v1_rating_proto protoreflect.FileDescriptor

const file_proto_rating_v1_rating_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/rating/v1/rating.proto\x12\trating.v1\"5\n" +
	"\x16GetPlayerRatingRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"\x9d\x01\n" +
	"\x17GetPlayerRatingResponse\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x05R\x06rating\x12!\n" +
	"\fgames_played\x18\x03 \x01(\x05R\vgamesPlayed\x12\x12\n" +
	"\x04wins\x18\x04 \x01(\x05R\x04wins\x12\x16\n" +
	"\x06losses\x18\x05 \x01(\x05R\x06losses2i\n" +
	"\rRatingService\x12X\n" +
	"\x0fGetPlayerRating\x12!.rating.v1.GetPlayerRatingRequest\x1a\".rating.v1.GetPlayerRatingResponseBEZCgithub.com/ErenKarakus1/Matchmaking-System/proto/rating/v1;ratingv1b\x06proto3"

var (
	file_proto_rating_v1_rating_proto_rawDescOnce sync.Once
	file_proto_rating_v1_rating_proto_rawDescData []byte
)

func file_proto_rating_v1_rating_proto_rawDescGZIP() []byte {
	file_proto_rating_v1_rating_proto_rawDescOnce.Do(func() {
		file_proto_rating_v1_rating_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rating_v1_rating_proto_rawDesc), len(file_proto_rating_v1_rating_proto_rawDesc)))
	})
	return file_proto_rating_v1_rating_proto_rawDescData
}

var file_proto_rating_v1_rating_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rating_v1_rating_proto_goTypes = []any{
	(*GetPlayerRatingRequest)(nil),  // 0: rating.v1.GetPlayerRatingRequest
	(*GetPlayerRatingResponse)(nil), // 1: rating.v1.GetPlayerRatingResponse
}
var file_proto_rating_v1_rating_proto_depIdxs = []int32{
	0, // 0: rating.v1.RatingService.GetPlayerRating:input_type -> rating.v1.GetPlayerRatingRequest
	1, // 1: rating.v1.RatingService.GetPlayerRating:output_type -> rating.v1.GetPlayerRatingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rating_v1_rating_proto_init() }
func file_proto_rating_v1_rating_proto_init() {
	if File_proto_rating_v1_rating_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rating_v1_rating_proto_rawDesc), len(file_proto_rating_v1_rating_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rating_v1_rating_proto_goTypes,
		DependencyIndexes: file_proto_rating_v1_rating_proto_depIdxs,
		MessageInfos:      file_proto_rating_v1_rating_proto_msgTypes,
	}.Build()
	File_proto_rating_v1_rating_proto = out.File
	file_proto_rating_v1_rating_proto_goTypes = nil
	file_proto_rating_v1_rating_proto_depIdxs = nil
}
